Repository wantedPreOnboarding/19_05th_shop, pull requests merged in 2022-03, with the labels that each got.

#52 [다빈] Modify - 고객센터 정적 페이지로 변경
  pages/contacts/index.tsx
  pages/contacts/index.type.ts
Labels: enhancement

#54 [수임] refactor 땡철이 관련 카데고리 리스트 뷰 변경
  apis/models/Categories.type.ts
  components/categories/Categories.styled.ts
  components/common/AppLayout/TitleBar/TitleBar.styled.ts
  components/index/DiscountItem/DiscountItem.tsx
  pages/categories/[category1Id].tsx
  yarn.lock
Labels: refactor

#56 [영종] Refactor, Add - (brands, categories, Item) 페이지 초기렌더 속도 개선, robots, sitemap 추가
  .eslintrc.json
  components/categories/Categories.type.ts
  components/common/AppLayout/AppLayout.tsx
  components/items/OptionViewer/OptionViewer.tsx
  components/items/index.ts
  cypress/integration/index.spec.js
  cypress/integration/index.spec.ts
  cypress/integration/items.spec.ts
  cypress/integration/nav.spec.ts
  cypress/support/commands.js
  package.json
  pages/_document.tsx
  pages/brands/[category2Id].tsx
  pages/categories/[category1Id].tsx
  pages/items/[conItemId].tsx
  robots.txt
  sitemap.xml
  yarn.lock
Labels: enhancement, refactor

#57 [수임] refactor - index api호출 부분 useSWR 적용
  pages/index.tsx
Labels: refactor

#58 [수임] refactor - 메인 배너 무한 슬라이드로 변경
  components/index/BannerSlider/BannerSlider.styled.ts
  components/index/BannerSlider/BannerSlider.tsx
  components/index/BannerSlider/BannerSlider.type.ts
  pages/index.tsx
Labels: enhancement

#59 [영종] Refactor - Page 컴포넌트 역할 명확히 변경
  apis/models/Item.type.ts
  apis/requestAPIs/item.ts
  components/brands/Brand.type.ts
  components/brands/BrandList.type.ts
  components/brands/index.styled.ts
  components/brands/index.tsx
  components/brands/index.type.ts
  components/categories/Categories.type.ts
  components/categories/index.styled.ts
  components/categories/index.tsx
  components/categories/index.type.ts
  components/contacts/index.styled.tsx
  components/contacts/index.tsx
  components/contacts/index.type.ts
  components/contacts/innerPaths.ts
  components/item/OptionSelector/OptionSelector.styled.ts
  components/item/OptionSelector/OptionSelector.tsx
  components/item/OptionSelector/OptionSelector.type.ts
  components/item/OptionViewer/OptionViewer.tsx
  components/item/OptionViewer/OptionsViewer.styled.ts
  components/item/SelectedOptionViewer/SelectedOptionViewer.styled.ts
  components/item/SelectedOptionViewer/SelectedOptionViewer.tsx
  components/item/SelectedOptionViewer/SelectedOptionViewer.type.ts
  components/item/TextsSection/TextsSection.styled.ts
  components/item/TextsSection/TextsSection.tsx
  components/item/TextsSection/TextsSection.type.ts
  components/item/index.styled.tsx
  components/item/index.tsx
  components/item/index.type.tsx
  components/item/innerPaths.ts
  components/items/Items.type.tsx
  pages/_document.tsx
  pages/brands/[category2Id].tsx
  pages/categories/[category1Id].tsx
  pages/contacts/index.tsx
  pages/index.tsx
  pages/item/[conItemId].tsx
Labels: refactor
